# List all files in the source folder
yosys read_verilog "../verilog_source/subterranean_round.v"
yosys read_verilog "../verilog_source/subterranean_round_1_xor.v"
yosys read_verilog "../verilog_source/subterranean_round_2_xor.v"
yosys read_verilog "../verilog_source/subterranean_rounds_simple_1.v"
yosys read_verilog "../verilog_source/subterranean_rounds_simple_2.v"
yosys read_verilog "../verilog_source/subterranean_rounds_simple_4.v"
yosys read_verilog "../verilog_source/subterranean64_rounds_simple_2.v"
yosys read_verilog "../verilog_source/subterranean_stream_state_machine.v"
yosys read_verilog "../verilog_source/subterranean_stream.v"
yosys read_verilog "../verilog_source/subterranean_lwc_buffer_in.v"
yosys read_verilog "../verilog_source/subterranean_lwc_buffer_out.v"
yosys read_verilog "../verilog_source/subterranean_lwc_state_machine.v"
yosys read_verilog "../verilog_source/subterranean_lwc.v"
